### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by rebdev** [vollnhals/dependent-fields-rails#2]
Hey, thanks for this gem, it looks like exactly what I'm looking for, but I'm having trouble getting it going. I'm actually learning both Rails and JQuery at the same time, so undoubtedly lack of knowledge between the two is where my problem is stemming from, but I'm usually able to work stuff out given an example or two. Wondered if you might be able to add one, or clarify something?

Where I start getting lost is: 

$ ->
    DependentFields.bind()

Is this actually supposed to be copied as-is into some file?

Cheers, appreciate any help you can offer!

**Comment by vollnhals** [comment]
Hi,

all examples on the github site are written in coffee script so that may have confused you.

If you have followed steps 1 to 3 then you can do the following:

open app/assests/javascripts/application.js
and paste the following javascript on the bottom:

$(document).ready(function() {
    DependentFields.bind()
}

This code just calls DependFields.bind as soon as the DOM is ready.
Now you should be setup and can use the functionality.

For an example you could use the following html code:

<input id="filing_priority_enabled" name="filing[priority_enabled]" type="checkbox" value="1">

<div class="js-dependent-fields" data-checkbox-id="filing_priority_enabled" data-checkbox-value="true">
<h1>This text is only shown if the checkbox above is checked.</h1>
</div>

It's just a checkbox with a div below. The div below is automatically shown / hidden based on the checkbox.
See the github page for other examples. Although all examples are written in slim templates (https://github.com/slim-template/slim) and use simple_form (https://github.com/plataformatec/simple_form)

If you would like to contribute better documentation that would be greatly appreciated.

Regards,
Lion

**Comment by rebdev** [comment]
Hey Lion, thanks for being so quick to help, it looks like I did have it all set up correctly, and all markup is looking like it should do at the front end, it's just still not working. Maybe an incompatibility or dependence I didn't check... I'll let you know if I figure out what it is; otherwise might have to figure out something else. Would be happy to discuss further but I'm aware it's quite likely me that's the problem so don't want to take up your time! Thanks again though!

**Comment by rebdev** [comment]
Yep, it was a dependency problem. My bad. Sorry!!! Underscore wasn't included properly. Got that happening and all works and it's beautiful. Thanks mate and thanks for the awesome gem!

**Comment by rebdev** [comment]
PS: Your update removing the Coffeescript from the documentation is also appreciated. Helped me know I was doing the right thing there and that I needed to look elsewhere for the source of the problem. Cheers!
